/*
 * This file is generated by jOOQ.
 */
package ch.rasc.webauthn.db;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ch.rasc.webauthn.db.tables.AppUser;
import ch.rasc.webauthn.db.tables.Credentials;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

  private static final long serialVersionUID = 1L;

  /**
   * The reference instance of <code>DEFAULT_SCHEMA</code>
   */
  public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

  /**
   * The table <code>APP_USER</code>.
   */
  public final AppUser APP_USER = AppUser.APP_USER;

  /**
   * The table <code>CREDENTIALS</code>.
   */
  public final Credentials CREDENTIALS = Credentials.CREDENTIALS;

  /**
   * No further instances allowed
   */
  private DefaultSchema() {
    super("", null);
  }

  @Override
  public Catalog getCatalog() {
    return DefaultCatalog.DEFAULT_CATALOG;
  }

  @Override
  public final List<Table<?>> getTables() {
    return Arrays.<Table<?>>asList(AppUser.APP_USER, Credentials.CREDENTIALS);
  }
}
