/*
 * This file is generated by jOOQ.
 */
package ch.rasc.webauthn.db;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.11.11" },
    comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultCatalog extends CatalogImpl {

  private static final long serialVersionUID = 306692743;

  /**
   * The reference instance of <code></code>
   */
  public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

  /**
   * The schema <code>webauthn</code>.
   */
  public final Webauthn WEBAUTHN = ch.rasc.webauthn.db.Webauthn.WEBAUTHN;

  /**
   * No further instances allowed
   */
  private DefaultCatalog() {
    super("");
  }

  @Override
  public final List<Schema> getSchemas() {
    List result = new ArrayList();
    result.addAll(getSchemas0());
    return result;
  }

  private final List<Schema> getSchemas0() {
    return Arrays.<Schema>asList(Webauthn.WEBAUTHN);
  }
}
