/*
 * This file is generated by jOOQ.
 */
package ch.rasc.webauthn.db;

import ch.rasc.webauthn.db.tables.Credentials;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling indexes of tables in webauthn.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

  // -------------------------------------------------------------------------
  // INDEX definitions
  // -------------------------------------------------------------------------

  public static final Index CREDENTIALS_APP_USER_ID = Internal.createIndex(
      DSL.name("app_user_id"), Credentials.CREDENTIALS,
      new OrderField[] { Credentials.CREDENTIALS.APP_USER_ID }, false);
}
