/*
 * This file is generated by jOOQ.
 */
package ch.rasc.webauthn.db;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import ch.rasc.webauthn.db.tables.AppUser;
import ch.rasc.webauthn.db.tables.Credentials;

/**
 * A class modelling indexes of tables of the <code>webauthn</code> schema.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.11.11" },
    comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

  // -------------------------------------------------------------------------
  // INDEX definitions
  // -------------------------------------------------------------------------

  public static final Index APP_USER_PRIMARY = Indexes0.APP_USER_PRIMARY;
  public static final Index APP_USER_USERNAME = Indexes0.APP_USER_USERNAME;
  public static final Index CREDENTIALS_APP_USER_ID = Indexes0.CREDENTIALS_APP_USER_ID;
  public static final Index CREDENTIALS_PRIMARY = Indexes0.CREDENTIALS_PRIMARY;

  // -------------------------------------------------------------------------
  // [#1459] distribute members to avoid static initialisers > 64kb
  // -------------------------------------------------------------------------

  private static class Indexes0 {
    public static Index APP_USER_PRIMARY = Internal.createIndex("PRIMARY",
        AppUser.APP_USER, new OrderField[] { AppUser.APP_USER.ID }, true);
    public static Index APP_USER_USERNAME = Internal.createIndex("username",
        AppUser.APP_USER, new OrderField[] { AppUser.APP_USER.USERNAME }, true);
    public static Index CREDENTIALS_APP_USER_ID = Internal.createIndex("app_user_id",
        Credentials.CREDENTIALS, new OrderField[] { Credentials.CREDENTIALS.APP_USER_ID },
        false);
    public static Index CREDENTIALS_PRIMARY = Internal.createIndex("PRIMARY",
        Credentials.CREDENTIALS, new OrderField[] { Credentials.CREDENTIALS.ID,
            Credentials.CREDENTIALS.APP_USER_ID },
        true);
  }
}
