/*
 * This file is generated by jOOQ.
 */
package ch.rasc.webauthn.db;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ch.rasc.webauthn.db.tables.AppUser;
import ch.rasc.webauthn.db.tables.Credentials;
import ch.rasc.webauthn.db.tables.records.AppUserRecord;
import ch.rasc.webauthn.db.tables.records.CredentialsRecord;

/**
 * A class modelling foreign key relationships and constraints of tables in webauthn.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  public static final UniqueKey<AppUserRecord> KEY_APP_USER_PRIMARY = Internal
      .createUniqueKey(AppUser.APP_USER, DSL.name("KEY_app_user_PRIMARY"),
          new TableField[] { AppUser.APP_USER.ID }, true);
  public static final UniqueKey<AppUserRecord> KEY_APP_USER_USERNAME = Internal
      .createUniqueKey(AppUser.APP_USER, DSL.name("KEY_app_user_username"),
          new TableField[] { AppUser.APP_USER.USERNAME }, true);
  public static final UniqueKey<CredentialsRecord> KEY_CREDENTIALS_PRIMARY = Internal
      .createUniqueKey(Credentials.CREDENTIALS, DSL.name("KEY_credentials_PRIMARY"),
          new TableField[] { Credentials.CREDENTIALS.ID,
              Credentials.CREDENTIALS.APP_USER_ID },
          true);

  // -------------------------------------------------------------------------
  // FOREIGN KEY definitions
  // -------------------------------------------------------------------------

  public static final ForeignKey<CredentialsRecord, AppUserRecord> CREDENTIALS_IBFK_1 = Internal
      .createForeignKey(Credentials.CREDENTIALS, DSL.name("credentials_ibfk_1"),
          new TableField[] { Credentials.CREDENTIALS.APP_USER_ID },
          Keys.KEY_APP_USER_PRIMARY, new TableField[] { AppUser.APP_USER.ID }, true);
}
