/*
 * This file is generated by jOOQ.
 */
package ch.rasc.webauthn.db;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import ch.rasc.webauthn.db.tables.AppUser;
import ch.rasc.webauthn.db.tables.Credentials;
import ch.rasc.webauthn.db.tables.records.AppUserRecord;
import ch.rasc.webauthn.db.tables.records.CredentialsRecord;

/**
 * A class modelling foreign key relationships and constraints of tables of the
 * <code>webauthn</code> schema.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.11.11" },
    comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

  // -------------------------------------------------------------------------
  // IDENTITY definitions
  // -------------------------------------------------------------------------

  public static final Identity<AppUserRecord, Long> IDENTITY_APP_USER = Identities0.IDENTITY_APP_USER;

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  public static final UniqueKey<AppUserRecord> KEY_APP_USER_PRIMARY = UniqueKeys0.KEY_APP_USER_PRIMARY;
  public static final UniqueKey<AppUserRecord> KEY_APP_USER_USERNAME = UniqueKeys0.KEY_APP_USER_USERNAME;
  public static final UniqueKey<CredentialsRecord> KEY_CREDENTIALS_PRIMARY = UniqueKeys0.KEY_CREDENTIALS_PRIMARY;

  // -------------------------------------------------------------------------
  // FOREIGN KEY definitions
  // -------------------------------------------------------------------------

  public static final ForeignKey<CredentialsRecord, AppUserRecord> CREDENTIALS_IBFK_1 = ForeignKeys0.CREDENTIALS_IBFK_1;

  // -------------------------------------------------------------------------
  // [#1459] distribute members to avoid static initialisers > 64kb
  // -------------------------------------------------------------------------

  private static class Identities0 {
    public static Identity<AppUserRecord, Long> IDENTITY_APP_USER = Internal
        .createIdentity(AppUser.APP_USER, AppUser.APP_USER.ID);
  }

  private static class UniqueKeys0 {
    public static final UniqueKey<AppUserRecord> KEY_APP_USER_PRIMARY = Internal
        .createUniqueKey(AppUser.APP_USER, "KEY_app_user_PRIMARY", AppUser.APP_USER.ID);
    public static final UniqueKey<AppUserRecord> KEY_APP_USER_USERNAME = Internal
        .createUniqueKey(AppUser.APP_USER, "KEY_app_user_username",
            AppUser.APP_USER.USERNAME);
    public static final UniqueKey<CredentialsRecord> KEY_CREDENTIALS_PRIMARY = Internal
        .createUniqueKey(Credentials.CREDENTIALS, "KEY_credentials_PRIMARY",
            Credentials.CREDENTIALS.ID, Credentials.CREDENTIALS.APP_USER_ID);
  }

  private static class ForeignKeys0 {
    public static final ForeignKey<CredentialsRecord, AppUserRecord> CREDENTIALS_IBFK_1 = Internal
        .createForeignKey(ch.rasc.webauthn.db.Keys.KEY_APP_USER_PRIMARY,
            Credentials.CREDENTIALS, "credentials_ibfk_1",
            Credentials.CREDENTIALS.APP_USER_ID);
  }
}
