/*
 * This file is generated by jOOQ.
 */
package ch.rasc.webauthn.db;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ch.rasc.webauthn.db.tables.AppUser;
import ch.rasc.webauthn.db.tables.Credentials;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.11.11" },
    comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Webauthn extends SchemaImpl {

  private static final long serialVersionUID = 1920898838;

  /**
   * The reference instance of <code>webauthn</code>
   */
  public static final Webauthn WEBAUTHN = new Webauthn();

  /**
   * The table <code>webauthn.app_user</code>.
   */
  public final AppUser APP_USER = ch.rasc.webauthn.db.tables.AppUser.APP_USER;

  /**
   * The table <code>webauthn.credentials</code>.
   */
  public final Credentials CREDENTIALS = ch.rasc.webauthn.db.tables.Credentials.CREDENTIALS;

  /**
   * No further instances allowed
   */
  private Webauthn() {
    super("webauthn", null);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Catalog getCatalog() {
    return DefaultCatalog.DEFAULT_CATALOG;
  }

  @Override
  public final List<Table<?>> getTables() {
    List result = new ArrayList();
    result.addAll(getTables0());
    return result;
  }

  private final List<Table<?>> getTables0() {
    return Arrays.<Table<?>>asList(AppUser.APP_USER, Credentials.CREDENTIALS);
  }
}
