/*
 * This file is generated by jOOQ.
 */
package ch.rasc.webauthn.db.tables.records;

import ch.rasc.webauthn.db.tables.AppUser;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppUserRecord extends UpdatableRecordImpl<AppUserRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>webauthn.app_user.id</code>.
   */
  public void setId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>webauthn.app_user.id</code>.
   */
  public Long getId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>webauthn.app_user.username</code>.
   */
  public void setUsername(String value) {
    set(1, value);
  }

  /**
   * Getter for <code>webauthn.app_user.username</code>.
   */
  public String getUsername() {
    return (String) get(1);
  }

  /**
   * Setter for <code>webauthn.app_user.recovery_token</code>.
   */
  public void setRecoveryToken(byte[] value) {
    set(2, value);
  }

  /**
   * Getter for <code>webauthn.app_user.recovery_token</code>.
   */
  public byte[] getRecoveryToken() {
    return (byte[]) get(2);
  }

  /**
   * Setter for <code>webauthn.app_user.registration_start</code>.
   */
  public void setRegistrationStart(LocalDateTime value) {
    set(3, value);
  }

  /**
   * Getter for <code>webauthn.app_user.registration_start</code>.
   */
  public LocalDateTime getRegistrationStart() {
    return (LocalDateTime) get(3);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached AppUserRecord
   */
  public AppUserRecord() {
    super(AppUser.APP_USER);
  }

  /**
   * Create a detached, initialised AppUserRecord
   */
  public AppUserRecord(Long id, String username, byte[] recoveryToken,
      LocalDateTime registrationStart) {
    super(AppUser.APP_USER);

    setId(id);
    setUsername(username);
    setRecoveryToken(recoveryToken);
    setRegistrationStart(registrationStart);
    resetChangedOnNotNull();
  }
}
