CREATE TABLE app_user (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username                VARCHAR(255) NOT NULL,
    recovery_token          BYTEA NULL,
    registration_start      TIMESTAMP NULL,
    PRIMARY KEY(id),
    UNIQUE(username)
);

CREATE TABLE credentials (
    id              BYTEA NOT NULL,
    app_user_id     BIGINT         NOT NULL,
    webauthn_user_id BYTEA NOT NULL,
    count           BIGINT     NOT NULL,
    public_key_cose BYTEA NOT NULL,
    transports      VARCHAR(255),
    UNIQUE(webauthn_user_id),
    PRIMARY KEY(id, app_user_id),
    FOREIGN KEY (app_user_id) REFERENCES app_user(id) ON DELETE CASCADE
);
