/*
 * This file is generated by jOOQ.
 */
package ch.rasc.webauthn.db.tables;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ch.rasc.webauthn.db.DefaultSchema;
import ch.rasc.webauthn.db.Indexes;
import ch.rasc.webauthn.db.Keys;
import ch.rasc.webauthn.db.tables.records.CredentialsRecord;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.11.11" },
    comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Credentials extends TableImpl<CredentialsRecord> {

  private static final long serialVersionUID = -170078067;

  /**
   * The reference instance of <code>CREDENTIALS</code>
   */
  public static final Credentials CREDENTIALS = new Credentials();

  /**
   * The class holding records for this type
   */
  @Override
  public Class<CredentialsRecord> getRecordType() {
    return CredentialsRecord.class;
  }

  /**
   * The column <code>CREDENTIALS.ID</code>.
   */
  public final TableField<CredentialsRecord, byte[]> ID = createField("ID",
      org.jooq.impl.SQLDataType.VARBINARY.nullable(false), this, "");

  /**
   * The column <code>CREDENTIALS.APP_USER_ID</code>.
   */
  public final TableField<CredentialsRecord, Long> APP_USER_ID = createField(
      "APP_USER_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

  /**
   * The column <code>CREDENTIALS.COUNT</code>.
   */
  public final TableField<CredentialsRecord, Long> COUNT = createField("COUNT",
      org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

  /**
   * The column <code>CREDENTIALS.PUBLIC_KEY_COSE</code>.
   */
  public final TableField<CredentialsRecord, byte[]> PUBLIC_KEY_COSE = createField(
      "PUBLIC_KEY_COSE", org.jooq.impl.SQLDataType.VARBINARY.nullable(false), this, "");

  /**
   * Create a <code>CREDENTIALS</code> table reference
   */
  public Credentials() {
    this(DSL.name("CREDENTIALS"), null);
  }

  /**
   * Create an aliased <code>CREDENTIALS</code> table reference
   */
  public Credentials(String alias) {
    this(DSL.name(alias), CREDENTIALS);
  }

  /**
   * Create an aliased <code>CREDENTIALS</code> table reference
   */
  public Credentials(Name alias) {
    this(alias, CREDENTIALS);
  }

  private Credentials(Name alias, Table<CredentialsRecord> aliased) {
    this(alias, aliased, null);
  }

  private Credentials(Name alias, Table<CredentialsRecord> aliased,
      Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""));
  }

  public <O extends Record> Credentials(Table<O> child,
      ForeignKey<O, CredentialsRecord> key) {
    super(child, key, CREDENTIALS);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Schema getSchema() {
    return DefaultSchema.DEFAULT_SCHEMA;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public List<Index> getIndexes() {
    return Arrays.<Index>asList(Indexes.CONSTRAINT_INDEX_9, Indexes.PRIMARY_KEY_9);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public UniqueKey<CredentialsRecord> getPrimaryKey() {
    return Keys.CONSTRAINT_9;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public List<UniqueKey<CredentialsRecord>> getKeys() {
    return Arrays.<UniqueKey<CredentialsRecord>>asList(Keys.CONSTRAINT_9);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public List<ForeignKey<CredentialsRecord, ?>> getReferences() {
    return Arrays.<ForeignKey<CredentialsRecord, ?>>asList(Keys.CONSTRAINT_91);
  }

  public AppUser appUser() {
    return new AppUser(this, Keys.CONSTRAINT_91);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Credentials as(String alias) {
    return new Credentials(DSL.name(alias), this);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Credentials as(Name alias) {
    return new Credentials(alias, this);
  }

  /**
   * Rename this table
   */
  @Override
  public Credentials rename(String name) {
    return new Credentials(DSL.name(name), null);
  }

  /**
   * Rename this table
   */
  @Override
  public Credentials rename(Name name) {
    return new Credentials(name, null);
  }
}
