/*
 * This file is generated by jOOQ.
 */
package ch.rasc.webauthn.db.tables;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ch.rasc.webauthn.db.DefaultSchema;
import ch.rasc.webauthn.db.Keys;
import ch.rasc.webauthn.db.tables.records.CredentialsRecord;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Credentials extends TableImpl<CredentialsRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * The reference instance of <code>CREDENTIALS</code>
   */
  public static final Credentials CREDENTIALS = new Credentials();

  /**
   * The class holding records for this type
   */
  @Override
  public Class<CredentialsRecord> getRecordType() {
    return CredentialsRecord.class;
  }

  /**
   * The column <code>CREDENTIALS.ID</code>.
   */
  public final TableField<CredentialsRecord, byte[]> ID = createField(DSL.name("ID"),
      SQLDataType.VARBINARY.nullable(false), this, "");

  /**
   * The column <code>CREDENTIALS.APP_USER_ID</code>.
   */
  public final TableField<CredentialsRecord, Long> APP_USER_ID = createField(
      DSL.name("APP_USER_ID"), SQLDataType.BIGINT.nullable(false), this, "");

  /**
   * The column <code>CREDENTIALS.COUNT</code>.
   */
  public final TableField<CredentialsRecord, Long> COUNT = createField(DSL.name("COUNT"),
      SQLDataType.BIGINT.nullable(false), this, "");

  /**
   * The column <code>CREDENTIALS.PUBLIC_KEY_COSE</code>.
   */
  public final TableField<CredentialsRecord, byte[]> PUBLIC_KEY_COSE = createField(
      DSL.name("PUBLIC_KEY_COSE"), SQLDataType.VARBINARY.nullable(false), this, "");

  private Credentials(Name alias, Table<CredentialsRecord> aliased) {
    this(alias, aliased, null);
  }

  private Credentials(Name alias, Table<CredentialsRecord> aliased,
      Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  /**
   * Create an aliased <code>CREDENTIALS</code> table reference
   */
  public Credentials(String alias) {
    this(DSL.name(alias), CREDENTIALS);
  }

  /**
   * Create an aliased <code>CREDENTIALS</code> table reference
   */
  public Credentials(Name alias) {
    this(alias, CREDENTIALS);
  }

  /**
   * Create a <code>CREDENTIALS</code> table reference
   */
  public Credentials() {
    this(DSL.name("CREDENTIALS"), null);
  }

  public <O extends Record> Credentials(Table<O> child,
      ForeignKey<O, CredentialsRecord> key) {
    super(child, key, CREDENTIALS);
  }

  @Override
  public Schema getSchema() {
    return DefaultSchema.DEFAULT_SCHEMA;
  }

  @Override
  public UniqueKey<CredentialsRecord> getPrimaryKey() {
    return Keys.CONSTRAINT_9;
  }

  @Override
  public List<UniqueKey<CredentialsRecord>> getKeys() {
    return Arrays.<UniqueKey<CredentialsRecord>>asList(Keys.CONSTRAINT_9);
  }

  @Override
  public List<ForeignKey<CredentialsRecord, ?>> getReferences() {
    return Arrays.<ForeignKey<CredentialsRecord, ?>>asList(Keys.CONSTRAINT_91);
  }

  public AppUser appUser() {
    return new AppUser(this, Keys.CONSTRAINT_91);
  }

  @Override
  public Credentials as(String alias) {
    return new Credentials(DSL.name(alias), this);
  }

  @Override
  public Credentials as(Name alias) {
    return new Credentials(alias, this);
  }

  /**
   * Rename this table
   */
  @Override
  public Credentials rename(String name) {
    return new Credentials(DSL.name(name), null);
  }

  /**
   * Rename this table
   */
  @Override
  public Credentials rename(Name name) {
    return new Credentials(name, null);
  }

  // -------------------------------------------------------------------------
  // Row4 type methods
  // -------------------------------------------------------------------------

  @Override
  public Row4<byte[], Long, Long, byte[]> fieldsRow() {
    return (Row4) super.fieldsRow();
  }
}
